### Site info:
title: XYLAN2004 
tagline: 我常常想起那天夕阳下的奔跑,那是我逝去的青春
author: XYLAN2004
email: xylan2004@gmail.com
description: "a private blog." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, xylan2004 "
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xylan2004.github.io" # the base hostname & protocol for your site


### Personal info and site tools info:
twitter_username: xylan2004
github_username:  xylan2004
disqus_shortname: xylan2004
favicon:     "/images/favicon.ico"
aboutme: Hi, this is xylan2004. . # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Resent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: xylan2004
      href: http://xylan2004.github.io/
      title: 我常常想起那天夕阳下的奔跑,那是我逝去的青春
    - name: xylan2004's website
      href: http://xylan2004.github.io/
      title: XYLAN2004


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
